# 반복문

In [1]:
# 반복문
sum1 <- 0
for(i in seq(1,10,1)){
    sum1 <- sum1+i
}
sum1

[1] 55

In [14]:
# 반복문 연습
dan <- 3
for (i in seq(1,9)){
    print(paste(dan,"X",i,"=",dan*i))
}

[1] "3 X 1 = 3"
[1] "3 X 2 = 6"
[1] "3 X 3 = 9"
[1] "3 X 4 = 12"
[1] "3 X 5 = 15"
[1] "3 X 6 = 18"
[1] "3 X 7 = 21"
[1] "3 X 8 = 24"
[1] "3 X 9 = 27"

In [17]:
gugu <- function(){
    dan <- readline("단을 입력하세요") # 사용자로 부터 입력 받는 함수
    dan <- as.integer(dan)
    for (i in seq(1,9)){
        print(paste(dan,"X",i,"=",dan*i))
    }
}

In [20]:
gugu()

단을 입력하세요4
[1] "4 X 1 = 4"
[1] "4 X 2 = 8"
[1] "4 X 3 = 12"
[1] "4 X 4 = 16"
[1] "4 X 5 = 20"
[1] "4 X 6 = 24"
[1] "4 X 7 = 28"
[1] "4 X 8 = 32"
[1] "4 X 9 = 36"

In [ ]:
 print(paste(i,"X",k,"=",i*k)

In [37]:
gugu1 <- function(){
    for (i in seq(2,9)){
        print(paste(rep("=",i))
        for (k in seq(1,9)){
            print(paste(i,"X",k,"=",k*i))
        }
    }
}

In [38]:
gugu1()

[1] "=" "="
[1] "2 X 1 = 2"
[1] "2 X 2 = 4"
[1] "2 X 3 = 6"
[1] "2 X 4 = 8"
[1] "2 X 5 = 10"
[1] "2 X 6 = 12"
[1] "2 X 7 = 14"
[1] "2 X 8 = 16"
[1] "2 X 9 = 18"
[1] "=" "=" "="
[1] "3 X 1 = 3"
[1] "3 X 2 = 6"
[1] "3 X 3 = 9"
[1] "3 X 4 = 12"
[1] "3 X 5 = 15"
[1] "3 X 6 = 18"
[1] "3 X 7 = 21"
[1] "3 X 8 = 24"
[1] "3 X 9 = 27"
[1] "=" "=" "=" "="
[1] "4 X 1 = 4"
[1] "4 X 2 = 8"
[1] "4 X 3 = 12"
[1] "4 X 4 = 16"
[1] "4 X 5 = 20"
[1] "4 X 6 = 24"
[1] "4 X 7 = 28"
[1] "4 X 8 = 32"
[1] "4 X 9 = 36"
[1] "=" "=" "=" "=" "="
[1] "5 X 1 = 5"
[1] "5 X 2 = 10"
[1] "5 X 3 = 15"
[1] "5 X 4 = 20"
[1] "5 X 5 = 25"
[1] "5 X 6 = 30"
[1] "5 X 7 = 35"
[1] "5 X 8 = 40"
[1] "5 X 9 = 45"
[1] "=" "=" "=" "=" "=" "="
[1] "6 X 1 = 6"
[1] "6 X 2 = 12"
[1] "6 X 3 = 18"
[1] "6 X 4 = 24"
[1] "6 X 5 = 30"
[1] "6 X 6 = 36"
[1] "6 X 7 = 42"
[1] "6 X 8 = 48"
[1] "6 X 9 = 54"
[1] "=" "=" "=" "=" "=" "=" "="
[1] "7 X 1 = 7"
[1] "7 X 2 = 14"
[1] "7 X 3 = 21"
[1] "7 X 4 = 28"
[1] "7 X 5 = 35"
[1] "7 X 6 = 42"
[1] "7 X 7 = 49"
[1] "7 X 8 = 56"
[1] "7 X 9 = 63"
[1] "=" "=" "=" "=" "=" "=" "=" "="
[1] "8 X 1 = 8"
[1] "8 X 2 = 16"
[1] "8 X 3 = 24"
[1] "8 X 4 = 32"
[1] "8 X 5 = 40"
[1] "8 X 6 = 48"
[1] "8 X 7 = 56"
[1] "8 X 8 = 64"
[1] "8 X 9 = 72"
[1] "=" "=" "=" "=" "=" "=" "=" "=" "="
[1] "9 X 1 = 9"
[1] "9 X 2 = 18"
[1] "9 X 3 = 27"
[1] "9 X 4 = 36"
[1] "9 X 5 = 45"
[1] "9 X 6 = 54"
[1] "9 X 7 = 63"
[1] "9 X 8 = 72"
[1] "9 X 9 = 81"

In [108]:
gugu2 <- function(){
    for (i in seq(2,9)){
        cat(paste(" ",i,"X",seq(1,9),"=",seq(1,9)*i,"\n"))
        cat(paste('------','\n'))
}
    }

In [12]:
gugu3 <- function(){
    for (i in seq(2,9)){
        cat(paste("\t",i,"X",seq(1,9),"=",seq(1,9)*i,"\n"))
        cat(paste('---------------------------------',"\n"))
    }
}

In [13]:
gugu3()

	 2 X 1 = 2
 	 2 X 2 = 4
 	 2 X 3 = 6
 	 2 X 4 = 8
 	 2 X 5 = 10
 	 2 X 6 = 12
 	 2 X 7 = 14
 	 2 X 8 = 16
 	 2 X 9 = 18
---------------------------------
	 3 X 1 = 3
 	 3 X 2 = 6
 	 3 X 3 = 9
 	 3 X 4 = 12
 	 3 X 5 = 15
 	 3 X 6 = 18
 	 3 X 7 = 21
 	 3 X 8 = 24
 	 3 X 9 = 27
---------------------------------
	 4 X 1 = 4
 	 4 X 2 = 8
 	 4 X 3 = 12
 	 4 X 4 = 16
 	 4 X 5 = 20
 	 4 X 6 = 24
 	 4 X 7 = 28
 	 4 X 8 = 32
 	 4 X 9 = 36
---------------------------------
	 5 X 1 = 5
 	 5 X 2 = 10
 	 5 X 3 = 15
 	 5 X 4 = 20
 	 5 X 5 = 25
 	 5 X 6 = 30
 	 5 X 7 = 35
 	 5 X 8 = 40
 	 5 X 9 = 45
---------------------------------
	 6 X 1 = 6
 	 6 X 2 = 12
 	 6 X 3 = 18
 	 6 X 4 = 24
 	 6 X 5 = 30
 	 6 X 6 = 36
 	 6 X 7 = 42
 	 6 X 8 = 48
 	 6 X 9 = 54
---------------------------------
	 7 X 1 = 7
 	 7 X 2 = 14
 	 7 X 3 = 21
 	 7 X 4 = 28
 	 7 X 5 = 35
 	 7 X 6 = 42
 	 7 X 7 = 49
 	 7 X 8 = 56
 	 7 X 9 = 63
---------------------------------
	 8 X 1 = 8
 	 8 X 2 = 16
 	 8 X 3 = 24
 	 8 X 4 = 32
 	 8 X 5 = 40
 	 8 X 6 = 48
 	 8 X 7 = 56
 	 8 X 8 = 64
 	 8 X 9 = 72
---------------------------------
	 9 X 1 = 9
 	 9 X 2 = 18
 	 9 X 3 = 27
 	 9 X 4 = 36
 	 9 X 5 = 45
 	 9 X 6 = 54
 	 9 X 7 = 63
 	 9 X 8 = 72
 	 9 X 9 = 81
---------------------------------

### 번외 반복문

In [100]:
# 반복문 while
sum1 <- 0
i <- 1
while(i<=10){
    sum1 <- sum1 + i
    i <- i + 1
}
sum1

[1] 55

In [101]:
# 반복문 repeat
sum1 <- 0
i <- 1
repeat{
    sum1 <- sum1+i
    i <- i+1
    if(i > 10)break
    
}
sum1

[1] 55

# 예제

#### 시험점수가 78, 95, 85, 65 일 경우 
#### 80점 이상이면 우수 , 그렇지 않으면 노력이라고 출력하시오   
#### (단 if문을 사용하지 말고 다른 함수를 사용)

In [137]:
score1=data.frame(x=c(78, 95, 85, 65))
judg <- function(){
    kk<-subset(score1, x>=80)
    cat(print("우수"))
    print(kk)
    jj<-subset(score1, x<80)
    cat(print("노력"))
    print(jj)
}

In [138]:
judg()

[1] "우수"
우수   x
2 95
3 85
[1] "노력"
노력   x
1 78
4 65

In [140]:
score <- c(78,95,85,65)
df = data.frame(score=score,결과=ifelse(score >= 80, '우수', '노력'))
df

  score 결과
1 78    노력
2 95    우수
3 85    우수
4 65    노력

#### exel.csv 를 읽어서 q1 칼럼의 데이터가 3보다 크거나 같으면 root값을 보여주고
#### 그렇지 않으면 원래 값을 보여주라

In [141]:
root1=read.csv('..//Data//excel.csv')

In [142]:
root1

    q1 q2 q3 q4 q5
1   2  4  4  2  2
2   1  2  2  2  2
3   2  3  4  3  3
4   3  5  5  3  3
5   3  2  4  4  4
6   4  3  3  4  2
7   3  4  4  2  2
8   4  2  4  4  4
9   4  4  5  3  4
10  4  2  4  2  3
11  4  4  4  3  3
12  3  1  4  3  4
13  3  2  4  3  4
14  3  4  3  4  5
15  1  3  2  2  3
16  3  4  2  3  4
17  3  2  1  1  3
18  3  3  3  4  3
19  2  2  4  3  2
20  3  4  4  3  4
21  3  4  5  2  4
22  4  3  4  2  3
23  2  2  2  1  4
24  2  3  4  3  5
25  3  4  4  2  4
26  4  2  3  3  2
27  4  4  4  4  3
28  4  4  5  3  3
29  3  2  2  3  4
30  3  2  4  3  5
⋮   ⋮  ⋮  ⋮  ⋮  ⋮
373 4  4  3  4  5
374 2  3  4  3  3
375 2  4  5  3  5
376 3  3  4  2  3
377 3  2  2  2  3
378 3  2  4  2  3
379 2  4  5  2  2
380 1  2  3  1  3
381 3  1  2  3  5
382 4  3  3  3  5
383 3  4  4  3  3
384 3  4  3  4  3
385 2  2  2  2  4
386 4  3  5  4  2
387 3  2  3  3  4
388 2  4  4  3  2
389 3  2  2  1  4
390 3  2  4  2  4
391 1  2  2  2  2
392 3  2  4  3  4
393 2  4  4  3  4
394 4  3  5  3  2
395 3  1  2  1  1
396 3  4  4  3  2
397 2  3  5  2  4
398 4  3  3  2  4
399 2  4  4  2  3
400 2  2  5  2  4
401 2  3  4  2  4
402 2  2  4  2  4

In [154]:
data.frame(root1,결과=ifelse(root1[,1] >= 3, sqrt(root1[,1]), root1[,1]))

    q1 q2 q3 q4 q5 결과
1   2  4  4  2  2  2.000000
2   1  2  2  2  2  1.000000
3   2  3  4  3  3  2.000000
4   3  5  5  3  3  1.732051
5   3  2  4  4  4  1.732051
6   4  3  3  4  2  2.000000
7   3  4  4  2  2  1.732051
8   4  2  4  4  4  2.000000
9   4  4  5  3  4  2.000000
10  4  2  4  2  3  2.000000
11  4  4  4  3  3  2.000000
12  3  1  4  3  4  1.732051
13  3  2  4  3  4  1.732051
14  3  4  3  4  5  1.732051
15  1  3  2  2  3  1.000000
16  3  4  2  3  4  1.732051
17  3  2  1  1  3  1.732051
18  3  3  3  4  3  1.732051
19  2  2  4  3  2  2.000000
20  3  4  4  3  4  1.732051
21  3  4  5  2  4  1.732051
22  4  3  4  2  3  2.000000
23  2  2  2  1  4  2.000000
24  2  3  4  3  5  2.000000
25  3  4  4  2  4  1.732051
26  4  2  3  3  2  2.000000
27  4  4  4  4  3  2.000000
28  4  4  5  3  3  2.000000
29  3  2  2  3  4  1.732051
30  3  2  4  3  5  1.732051
⋮   ⋮  ⋮  ⋮  ⋮  ⋮  ⋮
373 4  4  3  4  5  2.000000
374 2  3  4  3  3  2.000000
375 2  4  5  3  5  2.000000
376 3  3  4  2  3  1.732051
377 3  2  2  2  3  1.732051
378 3  2  4  2  3  1.732051
379 2  4  5  2  2  2.000000
380 1  2  3  1  3  1.000000
381 3  1  2  3  5  1.732051
382 4  3  3  3  5  2.000000
383 3  4  4  3  3  1.732051
384 3  4  3  4  3  1.732051
385 2  2  2  2  4  2.000000
386 4  3  5  4  2  2.000000
387 3  2  3  3  4  1.732051
388 2  4  4  3  2  2.000000
389 3  2  2  1  4  1.732051
390 3  2  4  2  4  1.732051
391 1  2  2  2  2  1.000000
392 3  2  4  3  4  1.732051
393 2  4  4  3  4  2.000000
394 4  3  5  3  2  2.000000
395 3  1  2  1  1  1.732051
396 3  4  4  3  2  1.732051
397 2  3  5  2  4  2.000000
398 4  3  3  2  4  2.000000
399 2  4  4  2  3  2.000000
400 2  2  5  2  4  2.000000
401 2  3  4  2  4  2.000000
402 2  2  4  2  4  2.000000

In [159]:
data.frame(root1,결과=ifelse(root1[,1] >= 2&root1[,1] <= 4, (root1[,1])*(root1[,1]), root1[,1]))

    q1 q2 q3 q4 q5 결과
1   2  4  4  2  2   4
2   1  2  2  2  2   1
3   2  3  4  3  3   4
4   3  5  5  3  3   9
5   3  2  4  4  4   9
6   4  3  3  4  2  16
7   3  4  4  2  2   9
8   4  2  4  4  4  16
9   4  4  5  3  4  16
10  4  2  4  2  3  16
11  4  4  4  3  3  16
12  3  1  4  3  4   9
13  3  2  4  3  4   9
14  3  4  3  4  5   9
15  1  3  2  2  3   1
16  3  4  2  3  4   9
17  3  2  1  1  3   9
18  3  3  3  4  3   9
19  2  2  4  3  2   4
20  3  4  4  3  4   9
21  3  4  5  2  4   9
22  4  3  4  2  3  16
23  2  2  2  1  4   4
24  2  3  4  3  5   4
25  3  4  4  2  4   9
26  4  2  3  3  2  16
27  4  4  4  4  3  16
28  4  4  5  3  3  16
29  3  2  2  3  4   9
30  3  2  4  3  5   9
⋮   ⋮  ⋮  ⋮  ⋮  ⋮  ⋮
373 4  4  3  4  5  16
374 2  3  4  3  3   4
375 2  4  5  3  5   4
376 3  3  4  2  3   9
377 3  2  2  2  3   9
378 3  2  4  2  3   9
379 2  4  5  2  2   4
380 1  2  3  1  3   1
381 3  1  2  3  5   9
382 4  3  3  3  5  16
383 3  4  4  3  3   9
384 3  4  3  4  3   9
385 2  2  2  2  4   4
386 4  3  5  4  2  16
387 3  2  3  3  4   9
388 2  4  4  3  2   4
389 3  2  2  1  4   9
390 3  2  4  2  4   9
391 1  2  2  2  2   1
392 3  2  4  3  4   9
393 2  4  4  3  4   4
394 4  3  5  3  2  16
395 3  1  2  1  1   9
396 3  4  4  3  2   9
397 2  3  5  2  4   4
398 4  3  3  2  4  16
399 2  4  4  2  3   4
400 2  2  5  2  4   4
401 2  3  4  2  4   4
402 2  2  4  2  4   4

In [177]:
score = c(85, 95, 98)
name= c('홍길동', '이순신',' 강감찬')
cbind(name,"->",score)

for (i in seq(1,3)){
    cat(paste(name[i],"->",score[i],"\n"))
}

cat(paste(name,"->",score,"\n"))

     name       score
[1,] 홍길동  -> 85
[2,] 이순신  -> 95
[3,]  강감찬 -> 98

홍길동 -> 85
이순신 -> 95
 강감찬 -> 98
홍길동 -> 85
 이순신 -> 95
  강감찬 -> 98

In [169]:
name[1]

[1] "홍길동"